version: '3.7'
services:
 app-backend:
  image: app-backend:latest
  build: .
  command: python Backend/manage.py runserver 0.0.0.0:8000
  ports:
   - "8000:8000"
 app-frontend:
  image: app-frontend:latest
  build: .
  ports:
   - "80:80"
